### ISSUE TITLE
Photo mosaic error

### ISSUE THREAD

**Issue by ferrbea** [sirulli/yoimages-search#1]
![screen shot 2015-04-26 at 17 08 44](https://cloud.githubusercontent.com/assets/5435160/7338268/378ebf06-ec47-11e4-9b54-6d3924416b35.png)
As shown in screenshot.

**Comment by fagia** [comment]
ready to be tested, fixed using css3 column-count property that has support in IE10+ (http://caniuse.com/#search=column-count)

**Comment by fagia** [comment]
seems to be fixed now, please test it again
